version: '3'

tasks:
  tidy:
    cmds:
      - go mod tidy

  build:
    deps: [tidy]
    cmds:
      - go build -o chargemeup cmd/chargemeup/main.go
    generates:
      - chargemeup
    silent: false

  clean:
    cmds:
      - rm chargemeup openchargemap-api.go

  test:
    cmds:
      - echo no tests yet
    silent: false

  build-deps:
    cmds:
      - go install github.com/deepmap/oapi-codegen/v2/cmd/oapi-codegen@latest

  oapi-codegen:
    deps: [build-deps]
    cmds:
      - oapi-codegen -generate 'types,client' -package openchargemap openchargemap.openapi.yml > openchargemap-api.go
    generates:
      - openchargemap-api.go

  default:
    cmds:
      - task: test
      - task: build

